### ISSUE TITLE
Small question about the construction of adjacency matrix and training code

### ISSUE THREAD

**Issue by duyichao** [AnthonyMRios/multi-label-zero-shot#3]
Hello, thank you for doing this great job. I have a few questions about this open source code:
1. How to construct mimic3_adj_matrix.pkl matrix
2. What are the specific meanings of lines 93 to 98 in train.py?
```python
    label_cooc = Y_train.T.dot(Y_train)
    topk = label_cooc.argsort(axis=1)[:, -10:]
    label_cooc[label_cooc > 0] = 0.
    label_cooc[np.repeat(np.arange(label_cooc.shape[0]), 10), topk.flatten()] = 1.
    label_cooc = label_cooc + np.eye(label_cooc.shape[0])
    label_cooc[label_cooc > 0] = 1.
```

Thanks.

**Comment by AnthonyMRios** [comment]
Hi,

For 1, you can use either an adjacency matrix or a normalized adjacency matrix of the ICD-9 hierarchy. I don't have the hierarchy laying around anymore, but, you should be able to find it online, or use UMLS to generate it.

For 2, Sorry for the confusion. That was just something I was playing with---checking if adding cooccurrence information could help improve the results. It didn't. I have removed it from the codebase. The code has a lot of things I was playing with at the time. If I have time, I will try to clean it up a bit.
