### ISSUE TITLE
sigmoid on prediction of each label 

### ISSUE THREAD

**Issue by xdwang0726** [AnthonyMRios/multi-label-zero-shot#4]
In the paper, when generate the sigmoid prediction of each label, in the formula, it is not clear what kind of multiplication it refers to in ```yˆi = sigmoid(eTi vi3), i = 1,...,L.```. (For instance, dimension of ```eT``` is [batch_size, q+d, num_labels] and ```v3``` is [q+d, num_labels], I am not quite get how the multiplication is expected to be like. ) I am wondering could you please explain and refer to the codes where this formula is implemented if possible? Thank you!

**Comment by AnthonyMRios** [comment]
Hi, do you mean to explain the formula in general, or via code? If you want to discuss this in detail, feel free to email me at anthonymrios@gmail.com.

The code is in Theano, so it can be convoluted (e.g., it requires the use dimshuffle and scan makes other parts of the code confusing). Let me use NumPy for simplicity. 

```python
import numpy as np

batch_size = 32
dim = 123 # lets assum dim = q+d
num_labels = 50

eT = np.random.random((batch_size, dim, num_labels))
v3 = np.random.random((dim, num_labels))

# Matrix Multiplication Method 1
result1 = []
for example in eT: # loop over examples in batch
    tmp = []
    for eT_example_label, v3_label in zip(example.T, v3.T): # loop over label vectors and example-label vectors.
         # I am ignoring the sigmoid for simplicity
        y_i = eT_example_label.dot(v3_label) # This is the main part "yˆi = sigmoid(eTi vi3), i = 1,...,L"
        tmp.append(y_i)
    result1.append(tmp)
result1 = np.array(result1) # result1  is batch_size x num_labels

# Matrix Multiplication Method 2  similar to the Theano implementation.
result2 = (eT.transpose(0,2,1) * v3.transpose(1,0)[None, :, :]).sum(axis=2) # ignoring sigmoid for simplicity
# result2 is batch_size x num_labels

print(np.allclose(result1, result2))
```

Edit: I believe the paper assumes batch size of 1 to simplify the notation. But I would need to check later to be sure.

**Comment by xdwang0726** [comment]
> Hi, do you mean to explain the formula in general, or via code? If you want to discuss this in detail, feel free to email me at [anthonymrios@gmail.com](mailto:anthonymrios@gmail.com).
> 
> The code is in Theano, so it can be convoluted (e.g., it requires the use dimshuffle and scan makes other parts of the code confusing). Let me use NumPy for simplicity.
> 
> ```python
> import numpy as np
> 
> batch_size = 32
> dim = 123 # lets assum dim = q+d
> num_labels = 50
> 
> eT = np.random.random((batch_size, dim, num_labels))
> v3 = np.random.random((dim, num_labels))
> 
> # Matrix Multiplication Method 1
> result1 = []
> for example in eT: # loop over examples in batch
>     tmp = []
>     for eT_example_label, v3_label in zip(example.T, v3.T): # loop over label vectors and example-label vectors.
>          # I am ignoring the sigmoid for simplicity
>         y_i = eT_example_label.dot(v3_label) # This is the main part "yˆi = sigmoid(eTi vi3), i = 1,...,L"
>         tmp.append(y_i)
>     result1.append(tmp)
> result1 = np.array(result1) # result1  is batch_size x num_labels
> 
> # Matrix Multiplication Method 2  similar to the Theano implementation.
> result2 = (eT.transpose(0,2,1) * v3.transpose(1,0)[None, :, :]).sum(axis=2) # ignoring sigmoid for simplicity
> # result2 is batch_size x num_labels
> 
> print(np.allclose(result1, result2))
> ```
> 
> Edit: I believe the paper assumes batch size of 1 to simplify the notation. But I would need to check later to be sure.

Thank you for your replay! It really helps! I just wondering if I understand correctly, the multiplication between ```eT``` and ```vT``` is not a matrix multiplication, it's like a row/column wise multiplication? Thanks!

**Comment by AnthonyMRios** [comment]
_I just wondering if I understand correctly, the multiplication between eT and vT is not a matrix multiplication, it's like a row/column wise multiplication?_

Yep, it is not standard matrix multiplication. Technically, assuming a batch size of 1, you could accomplish it with matrix multiplication, but you would only use the diagonal part of the resulting matrix. It is more efficient to use the methods in the code above.

Here is code with matrix multiplication and taking the diagonal (Method 3):

```python
import numpy as np

batch_size = 32
dim = 123 # lets assum dim = q+d
num_labels = 50

eT = np.random.random((batch_size, dim, num_labels))
v3 = np.random.random((dim, num_labels))

# Method 1
result1 = []
for example in eT: # loop over examples in batch
    tmp = []
    for eT_example_label, v3_label in zip(example.T, v3.T): # loop over label vectors and CNN-example-label vectors.
        y_i = eT_example_label.dot(v3_label) # I am ignoring the sigmoid for simplicity
        tmp.append(y_i)
    result1.append(tmp)
result1 = np.array(result1)

# Matrix Multiplication Method 2  similar to the Theano implementation.
result2 = (eT.transpose(0,2,1) * v3.transpose(1,0)[None, :, :]).sum(axis=2) # ignoring sigmoid for simplicity

print(np.allclose(result1, result2))
print(result2.shape)

# Matrix Multiplication Method 3
result3 = []
for example in eT: # loop over examples in batch
    result3.append(np.diag(example.T.dot(v3))) # I am ignoring the sigmoid for simplicity
result3 = np.array(result3)

print(result3.shape)
print(np.allclose(result2, result3))
```

**Comment by xdwang0726** [comment]
> _I just wondering if I understand correctly, the multiplication between eT and vT is not a matrix multiplication, it's like a row/column wise multiplication?_
> 
> Yep, it is not standard matrix multiplication. Technically, assuming a batch size of 1, you could accomplish it with matrix multiplication, but you would only use the diagonal part of the resulting matrix. It is more efficient to use the methods in the code above.
> 
> Here is code with matrix multiplication and taking the diagonal (Method 3):
> 
> ```python
> import numpy as np
> 
> batch_size = 32
> dim = 123 # lets assum dim = q+d
> num_labels = 50
> 
> eT = np.random.random((batch_size, dim, num_labels))
> v3 = np.random.random((dim, num_labels))
> 
> # Method 1
> result1 = []
> for example in eT: # loop over examples in batch
>     tmp = []
>     for eT_example_label, v3_label in zip(example.T, v3.T): # loop over label vectors and CNN-example-label vectors.
>         y_i = eT_example_label.dot(v3_label) # I am ignoring the sigmoid for simplicity
>         tmp.append(y_i)
>     result1.append(tmp)
> result1 = np.array(result1)
> 
> # Matrix Multiplication Method 2  similar to the Theano implementation.
> result2 = (eT.transpose(0,2,1) * v3.transpose(1,0)[None, :, :]).sum(axis=2) # ignoring sigmoid for simplicity
> 
> print(np.allclose(result1, result2))
> print(result2.shape)
> 
> # Matrix Multiplication Method 3
> result3 = []
> for example in eT: # loop over examples in batch
>     result3.append(np.diag(example.T.dot(v3))) # I am ignoring the sigmoid for simplicity
> result3 = np.array(result3)
> 
> print(result3.shape)
> print(np.allclose(result2, result3))
> ```

Thank you! It really helps!
